version: "3.3"
services:
  ecollect:
    image: 172.16.19.151:5000/ecollect:1.0.0
    container_name: ecollect
    restart: always
    ports:
      - "7000:80"
    networks:
    - ecol-network

  ecollect_apis:
    image: 172.16.19.151:5000/ecollect_apis:1.0.0
    container_name: ecollect_apis
    restart: always
    environment:
      - DB_HOST=192.168.0.12
      - DB_PORT=1521
      - DB_USER=ecol
      - DB_PASSWORD=ecol
      - DB_DATABASE=ORCLCDB.localdomain
    ports:
      - "8000:8000"
    networks:
    - ecol-network

  oracledb_node:
    image: 172.16.19.151:5000/oracledbnode:1.0.0
    container_name: oracledb_node
    restart: always
    environment:
      - DB_USER=ecol
      - DB_PASSWORD=ecol
      - DB_CONNECTIONSTRING=192.168.0.12:1521/ORCLCDB.localdomain
    ports:
      - "6001:6001"
    networks:
    - ecol-network

  uploads:
    image: 172.16.19.151:5000/uploads:1.0.0
    container_name: uploads
    restart: always
    environment:
      - CORS=http://localhost:7000
    volumes:
      - c:\logs:/var/uploads
    ports:
      - "4000:4000"
      - "5000:5000"
      - "5001:5001"
      - "3000:3000"
    networks:
    - ecol-network

  docxletters:
    image: 172.16.19.151:5000/docxletters:1.0.0
    container_name: docx
    restart: always
    volumes:
      - d:\demands:/app/demands/
    environment:
      - FILEPATH=/app/demands/
      - IMAGEPATH=/app/docxletters/routes/
    ports:
      - "8004:8004"
    networks:
    - ecol-network

  birt:
    container_name: birt
    image: 172.16.19.151:5000/birt:1.0.0
    volumes:
      - D:\angularprojects\birt\reports:/usr/local/tomcat/webapps/birt
    restart: always
    ports:
      - 8787:8080

networks:
  ecol-network:
    driver: bridge